### ISSUE TITLE
Edit a Comment -3 

### ISSUE THREAD

**Issue by stevebrownlee** [NSS-Day-Cohort-42/rare-media-moguls#33]
As a commenter I would like to be able to modify my Comments so that I can correct mistakes or add additional content.

**Given** the user is viewing the Comment list  
**When** they select the option to edit an Comment  
**Then** the user should be directed to a form and given the ability to change the Comment's information  

**Given** the user is finished updating the Comment information  
**When** they click the `Save` button  
**Then** the updated Comment should be saved to the database  
**And** the user should be redirected to the new Comment's details page

**Given** the user has decided not to edit the Comment  
**When** they click the `Cancel` button  
**Then** the user should be redirected back to the list page

Editable Information

* Subject
* Content

**Comment by ConnorBlakeney** [comment]
1) option to edit is clicked by user
2) user url changes to edit mode
3) user is directed to form where they can change information
4) user can resubmit clicking save and information is updated in database using PUT method
5) user is redirected to new comment detail page
6) user also has option to cancel edit, and if clicked will redirect back to link page
